### ISSUE TITLE
Use git to perform commits

### ISSUE THREAD

**Issue by iAtog** [LucFrsever3/Wardrobe#3]
Consider using git, I noticed that you delete the repository and re-upload to keep changes, with git you don't do that.

**Comment by PermisosDev** [comment]
+1

**Comment by ghost** [comment]
You should also follow the [Java Naming Conventions](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html) and use a library like [this one](https://github.com/unnamed/gui) for creating GUIs. 
P.S. Don't make your code look like [this](https://cdn.discordapp.com/attachments/698332180249575548/721191704002035752/else_if.mp4), please
